"""Update Client model with registration_date and due_date fields

Revision ID: 0c139a26b0cf
Revises: f20986ea6641
Create Date: 2025-05-07 16:09:11.766818

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0c139a26b0cf'
down_revision = 'f20986ea6641'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('client', schema=None) as batch_op:
        batch_op.add_column(sa.Column('registration_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('due_date', sa.Date(), nullable=True))
        batch_op.drop_column('date')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('client', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date', sa.VARCHAR(length=10), nullable=False))
        batch_op.drop_column('due_date')
        batch_op.drop_column('registration_date')

    # ### end Alembic commands ###
