"""Add created_at to announcement

Revision ID: 2d6cdbca57a9
Revises: 0c139a26b0cf
Create Date: 2025-05-15 16:42:28.355940

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2d6cdbca57a9'
down_revision = '0c139a26b0cf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('announcement', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))

    with op.batch_alter_table('document', schema=None) as batch_op:
        batch_op.alter_column('pdf_version',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('document', schema=None) as batch_op:
        batch_op.alter_column('pdf_version',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=True)

    with op.batch_alter_table('announcement', schema=None) as batch_op:
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###
